config/routes.rb
Rails.application.routes.draw do
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord

  validates :name, :make, :color, :model, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :set_cars, only: [:show, :new, :edit, :index, :create, :update]

  # GET /cars
  # GET /cars.json
  def index
    @car = Car.order(updated_at: :asc).last
    render :show
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @car = Car.find(params[:id])
  end

  def set_cars
    @cars = Car.all
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def car_params
    params.require(:car).permit(:name, :make, :color, :model, :follow_up_tags, :addons)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= simple_form_for @car,
                    html:    {
                        class: 'col-md-12 form-horizontal',
                        data:  {
                            'fv-framework':       'bootstrap',
                            'fv-icon-valid':      'fa fa-check',
                            'fv-icon-invalid':    'fa fa-times',
                            'fv-icon-validating': 'fa fa-refresh',
                            controller:           'cars',
                            target:               'cars.form'
                        },
                        id:    'car_form'
                    },
                    wrapper: :horizontal_form do |form| %>
  <%= form.error_notification %>

  <%= form.input :name,
                 input_html: {
                     data: {
                         'fv-notempty-message':  "can't be blank",
                         'fv-callback':          true,
                         'fv-callback-message':  'Must be unique',
                         'fv-callback-callback': 'Cars.verifyName'
                     }
                 },
                 required:   true
  %>

  <%= form.input :make,
                 collection: %w[ford mazda acura honda chevy dodge bmw lexus volvo],
                 input_html: {
                     data: {
                         'fv-notempty-message': 'Must be selected',
                         target:                'cars.make',
                         placeholder:           'Please Select...'
                     }
                 },
                 required:   true
  %>

  <%= form.input :color,
                 collection: %w[blue red green yellow purple orange white black grey],
                 input_html: {
                     data: {
                         'fv-notempty-message': 'Must be selected',
                         target:                'cars.color',
                         placeholder:           'Please Select...'
                     }
                 },
                 required:   true
  %>

  <%= form.input :model,
                 collection: %w[car truck compact sudan van minivan],
                 input_html: {
                     data: {
                         'fv-notempty-message': 'Must be selected',
                         target:                'cars.model',
                         placeholder:           'Please Select...'
                     }
                 },
                 required:   true
  %>

  <div class="form-group">
    <label class="col-sm-3 control-label select required">
      <abbr title="required">*</abbr> Addons
    </label>
    <div class="col-sm-9">
      <span>
        <%= select_tag 'addon_list',
                       options_for_select(%w[leather navigation sound rims rack],
                                          selected: form.object.addons&.split(',') || []),
                       {
                           multiple: 'multiple',
                           data:     {
                               'fv-notempty-message': 'Must have at least one addon',
                               target:                'cars.addons',
                               placeholder:           'Enter Addons...'
                           },
                           class:    'form-control',
                           required: true
                       }
        %>
      </span>
    </div>
  </div>
  <%= form.input :addons, as: :hidden, input_html: { data: { target: 'cars.addonsInput' } } %>

  <div class="form-group">
    <label class="col-sm-3 control-label select required">
      <abbr title="required">*</abbr> Follow Up Tags
    </label>
    <div class="col-sm-9">
      <span>
        <%= select_tag 'followup_tag_list',
                       options_for_select(form.object.follow_up_tags&.split(',') || [],
                                          selected: form.object.follow_up_tags&.split(',') || []),
                       {
                           multiple: 'multiple',
                           data:     {
                               'fv-notempty-message': 'Must have at least one follow up tag',
                               target:                'cars.follow',
                               placeholder:           'Enter Follow Up Tags...'
                           },
                           class:    'form-control',
                           required: true
                       }
        %>
      </span>
    </div>
  </div>
  <%= form.input :follow_up_tags, as: :hidden, input_html: { data: { target: 'cars.followInput' } } %>

  <%= form.button :button, 'Submit', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', cars_path, class: 'btn btn-default' %>
<% end %>

app/views/cars/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-md-4 panel-header">
        Edit <%= @car.name %>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/cars/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-md-4 panel-header">
        New Car
      </div>
    </div>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/cars/show.html.erb
<% if @car %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="row">
        <div class="col-md-4 panel-header">
          <%= @car.name %>
        </div>
        <div class="pull-right">
          <%= link_to "<i class='fa fa-pencil fa-lg fa-fw'></i>".html_safe,
                      edit_car_path(@car)
          %>
          <%= link_to "<i class='fa fa-trash fa-lg fa-fw'></i>".html_safe,
                      @car,
                      method: :delete, data: { confirm: 'Are you sure?' }
          %>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <dl class="dl-horizontal">
        <dt><strong>Make:</strong></dt>
        <dd><%= @car.make %></dd>
        <dt><strong>Color:</strong></dt>
        <dd><%= @car.color %></dd>
        <dt><strong>Model:</strong></dt>
        <dd><%= @car.model %></dd>
        <dt><strong>Addons:</strong></dt>
        <dd><%= @car.addons %></dd>
        <dt><strong>Follow Up Tags:</strong></dt>
        <dd><%= @car.follow_up_tags %></dd>
      </dl>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StimulusFormvalidation</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body data-controller-name="<%= controller_path %>" data-ctrlr-action="<%= action_name %>">
<div class="container-fluid">
  <%= yield(:controller) %>
</div>
</body>
</html>

app/views/layouts/cars.html.erb
<%= content_for :controller do %>
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading panel-heading-cars">
          <div class="row">
            <div class="col-md-6">
              <h4 class="panel-heading-text-buffer">Cars</h4>
            </div>
            <div class="col-md-6">
              <%= link_to "<span class='fa-stack fa-fw'><i class='fa fa-plus fa-lg'></i></span>".html_safe,
                          new_car_path,
                          class: 'btn-link pull-right'
              %>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <div class="list-group" id="cars_list">
            <% @cars.each do |car| %>
              <%= link_to car.name,
                          car,
                          class: "list-group-item #{'active' if @car.id == car.id}"
              %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <%= yield %>
    </div>
  </div>
<% end %>
<%= render template: 'layouts/application' %>